- name: "deploy FreeSHR client"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - bahmni-shr-client
  tags:
    - shr-client-deploy

- name: "deploy FreeSHR client individual"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - { role: bahmni-shr-client, when: box_tag_name == box_tag }
  tags:
    - shr-client-deploy-individual

- name: "deploy TR Feed client"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - bahmni-tr-feed-client
  tags:
    - tr-feed-client

- name: "deploy TR Feed client individual"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - { role: bahmni-tr-feed-client, when: box_tag_name == box_tag }
  tags:
    - tr-feed-client-individual

- name: "deploy TR and SHR client individual"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - { role: bahmni-deploy-omods, when: box_tag_name == box_tag }
  tags:
    - bahmni-omods-individual