- name: "deploy FreeSHR client"
  hosts: bahmni
  sudo: yes
  roles:
    - bahmni-shr-client
  tags:
    - shr-client-deploy

- name: "deploy TR Feed client"
  hosts: bahmni
  sudo: yes
  roles:
    - bahmni-tr-feed-client
  tags:
    - tr-feed-client

- name: "Setup address hierarchy data"
  hosts: bahmni-db
  sudo: yes
  vars:
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_locations_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" }
  tags:
    - shr-client-locations

- name: "Setup providers data"
  hosts: bahmni-db
  sudo: yes
  vars:
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_providers_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" }
  tags:
    - shr-client-providers

- name: "Setup facilities data"
  hosts: bahmni-db
  sudo: yes
  vars:
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_facilities_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" }
  tags:
    - shr-client-facilities

- name: "Setup concept data"
  hosts: bahmni-db
  sudo: yes
  vars:
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_concept_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" and implementation_config_name == implementation }
  tags:
    - shr-client-concept

- name: "Setup bdshr config"
  hosts: bahmni
  sudo: true
  roles:
    - { role: bahmni-deploy-config, when: is_host_active == "true"}
  tags:
    - bahmni-deploy-config
