
- name: "Setup address hierarchy data"
  hosts: bahmni-db
  become_user: root
  become: yes
  vars:
    data_source: "{{ data_file }}"
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    sql_file: "locations.sql"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" and box_tag_name == box_tag }
  tags:
    - shr-client-locations

- name: "Setup providers data"
  hosts: bahmni-db
  become_user: root
  become: yes
  vars:
    data_source: "{{ data_file }}"
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    sql_file: "providers.sql"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" and box_tag_name == box_tag }
  tags:
    - shr-client-providers

- name: "Setup facilities data"
  hosts: bahmni-db
  become_user: root
  become: yes
  vars:
    data_source: "{{ data_file }}"
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    sql_file: "facilities.sql"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" and box_tag_name == box_tag }
  tags:
    - shr-client-facilities

- name: "Setup concept data"
  hosts: bahmni-db
  become_user: root
  become: yes
  vars:
    data_source: "{{ data_file }}"
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    sql_file: "openrms_concept_data.sql"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: is_host_active == "true" and implementation_config_name == implementation and box_tag_name == box }
  tags:
    - shr-client-concept

#--------Needs to be changed------------  
- name: "Setup bdshr config"
  hosts: bahmni
  become_user: root
  become: yes
  roles:
    - { role: bahmni-deploy-config, when: implementation_config_name == implementation }
  tags:
    - bahmni-deploy-config
