---
# Needs to be passed all_omods as extra-vars from the command used to invoke this script
- hosts: bahmni
  sudo: True
  vars:
    bahmni_user: bahmni
  roles:
    - shr-client
  tags:
    - shr-client-deploy

- hosts: bahmni1
  sudo: True
  vars:
    bahmni_user: bahmni
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_locations_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: set_up_seed == "yes" }
  tags:
    - shr-client-locations

- hosts: bahmni1
  sudo: True
  vars:
    bahmni_user: bahmni
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_providers_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: set_up_seed == "yes" }
  tags:
    - shr-client-providers

- hosts: bahmni1
  sudo: True
  vars:
    bahmni_user: bahmni
    data_destination_dir: "{{ shr_client_seed_data_destination_dir }}"
    data_source_dir: "{{ shr_client_seed_data_source_dir }}"
    data_file: "{{ shr_client_facilities_seed_data_file }}"
    shr_client_database: "openmrs"
  roles:
    - { role: mysql-data-dump, when: set_up_seed == "yes" }
  tags:
    - shr-client-facilities
