---
- name: Copy mysql driver
  copy: src='mysql-connector-java-5.0.8-bin.jar' dest=/usr/share/java mode=755

- name: Copy migrations
  copy: src='{{environment}}-migrations.xml' dest=/tmp mode=755

- name: Apply migrations
  uri: url=http://localhost:8080/openmrs/index.htm return_content=true
  shell: liquibase --url="jdbc:mysql://localhost/terminologies" --username=root --password=password --changeLogFile=/tmp/{{environment}}-migrations.xml --classpath=/usr/share/java/mysql-connector-java-5.0.8-bin.jar update
