---
- name: Delete shr client omod
  shell: rm -f /home/{{ bahmni_user }}/.OpenMRS/modules/shrclient-*.omod
  sudo: yes

- name: Copy shr client omod
  copy: 
    src='{{ omod }}' 
    dest=/home/{{ bahmni_user }}/.OpenMRS/modules/ 
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Restart tomcat
  service: name=tomcat state=restarted
  when: is_host_active == "true"
