---
- name: Delete shr client omod
  shell: rm -f /opt/openmrs/modules/shrclient-*.omod

- name: Copy shr client omod
  copy: 
    src='{{ omod }}' 
    dest=/opt/openmrs/modules/
    mode=755
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Restart openmrs
  service: name=openmrs state=restarted
  when: is_host_active == "true"
