---

- name: Create '{{bdshr_config_home}}' dir
  command: mkdir -p {{bdshr_config_home}}

- name: Copy MCI properties
  copy: src=files/{{deployment_environment}}-mci.properties
    dest='{{bdshr_config_home}}'/mci.properties
    mode=755

- name: Copy SHR properties
  copy: src=files/{{deployment_environment}}-shr.properties
    dest='{{bdshr_config_home}}'/shr.properties
    mode=755

- name: Copy TR properties
  copy: src=files/{{deployment_environment}}-tr_atomfeed_properties.properties
    dest='{{bdshr_config_home}}'/tr_atomfeed_properties.properties
    mode=755

- name: Copy config
  copy: src={{ item }} dest=/packages/build mode=0777
  with_fileglob:
    - "{{ config_file }}"

- name: No tty
  lineinfile: backup=yes state=present dest=/etc/sudoers
              regexp='^Defaults    requiretty'
              line='#Defaults    requiretty'

- name: Deploy bdshr config
  shell:
    ./scripts/run-puppet-manifest.sh deploy-implementation
    chdir=/root/bahmni/bahmni-environment
  environment:
    BAHMNI_USER_NAME: '{{bahmni_user}}'
    IMPLEMENTATION_NAME: bdshr
  ignore_errors: yes

- name: Stop openerp service
  service: name=openerp state=stopped
