---

- name: Copy config
  copy: src={{ item }} dest=/packages/build mode=0777
  with_fileglob:
    - "{{ config_file }}"

- name: No tty
  lineinfile: backup=yes state=present dest=/etc/sudoers
              regexp='^Defaults    requiretty'
              line='#Defaults    requiretty'

- name: Deploy bdshr config
  shell:
    ./scripts/run-puppet-manifest.sh deploy-implementation
    chdir={{bahmni_home}}/bahmni-environment
  environment:
    BAHMNI_USER_NAME: '{{bahmni_user}}'
    IMPLEMENTATION_NAME: bdshr

- name: Stop openerp service
  service: name=openerp state=stopped
