---

- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - ruby
    - puppet
    - git
    - MySQL-python
    - wget

- name: Delete dirs
  command: rm -rf {{ item }}
  with_items:
    - '{{bahmni_home}}'/bahmni-environment
    - /packages/build
    - /bahmni_temp

- name: Create dirs
  command: mkdir -p {{ item }}
  with_items:
    - '{{bahmni_home}}'
    - /packages

- name: Git clone bahmni-environment
  command:
    git clone -b {{release_version}} https://github.com/Bhamni/bahmni-environment.git
    chdir='{{bahmni_home}}'

- name: Run Bahmni provision scripts
  # Assumption: /packages constains localrepo, servers, tools and python-packages
  shell:
    ./scripts/run-puppet-manifest.sh provision
    chdir='{{bahmni_home}}'/bahmni-environment
  environment:
    BAHMNI_USER_NAME: '{{bahmni_user}}'
    IMPLEMENTATION_NAME: jss

- name: Create openmrs db
  mysql_db: name=openmrs state=present login_user=root login_password=password

- name: Create openerp db
  postgresql_db: name=openerp

- name: Download bahmni build
  copy:
    src='{{bahmni_home}}'/release/bahmni-{{release_version}}.zip
    dest=/tmp/

- name: Unarchive bahmni build
  command:
    tar -xvf /tmp/bahmni-{{release_version}}.zip
    chdir=/packages
