---

- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - ruby
    - puppet
    - git
    - MySQL-python
    - wget

- name: Delete dirs
  command: rm -rf {{ item }}
  with_items:
    - /root/bahmni
    - /packages/build
    - /bahmni_temp

- name: Create /root/bahmni dir
  command: mkdir -p /root/bahmni

- name: Git clone bahmni-environment
  command:
    git clone -b {{release_version}} https://github.com/Bhamni/bahmni-environment.git
    chdir=/root/bahmni

- name: Run Bahmni provision scripts
  # Assumption: /packages constains localrepo, servers, tools and python-packages
  shell:
    ./scripts/run-puppet-manifest.sh provision
    chdir=/root/bahmni/bahmni-environment
  environment:
    BAHMNI_USER_NAME: '{{bahmni_user}}'
    IMPLEMENTATION_NAME: jss

- name: Create openmrs db
  mysql_db: name=openmrs state=present login_user=root login_password=password

- name: Create openerp db
  postgresql_db: name=openerp

- name: Run Bahmni download-build scripts
  shell:
    ./scripts/run-puppet-manifest.sh download-build
    chdir=/root/bahmni/bahmni-environment
  environment:
    BAHMNI_USER_NAME: '{{bahmni_user}}'
    IMPLEMENTATION_NAME: jss
