---
- name: Copy mci properties
  template:
    src=mci.j2 
    dest={{openmrs_properties_location}}/mci.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy shr properties
  template:
    src=shr.j2
    dest={{openmrs_properties_location}}/shr.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy facility registry properties
  template:
    src=fr.j2
    dest={{openmrs_properties_location}}/fr.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy location registry properties
  template:
    src=lr.j2
    dest={{openmrs_properties_location}}/lr.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy provider registry properties
  template:
    src=pr.j2
    dest={{openmrs_properties_location}}/pr.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy identity-server properties
  template:
    src=idp.j2
    dest={{openmrs_properties_location}}/identity.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy facility instance properties
  template:
    src=facility_instance.j2
    dest={{openmrs_properties_location}}/facility_instance.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: Copy terminology registry properties
  template:
    src=tr_atomfeed_properties.j2
    dest={{openmrs_properties_location}}/tr_atomfeed_properties.properties
    mode=644
    owner={{ bahmni_user }}
    group={{ bahmni_user }}

- name: "create hosts entries"
  lineinfile: 
    dest=/etc/hosts
    regexp="{{ item }}"
    line="{{ hostvars[item].host_ip_address }} {{ item }}"
    state=present
  with_items: groups['external-registries'] | default([])