---

- name: Copy config
  copy: src='{{ item }}' dest=/tmp/installer.sh mode=0777
  with_fileglob:
    - "{{ config_file }}"

- name: Deploy bdshr config
  shell:
    /tmp/installer.sh
  environment:
    FACTER_deploy_bahmni_openerp: "{{ deploy_openerp }}"
    FACTER_deploy_bahmni_openelis: "{{ deploy_openelis }}"
    FACTER_implementation_name: "{{ implementation_config_name }}"
    FACTER_bahmni_user_name: bahmni
