---

- name: Copy config
  copy: src={{ item }} dest=/packages/build mode=0777
  with_fileglob:
    - "{{ config_file }}"

- name: No tty
  lineinfile: backup=yes state=present dest=/etc/sudoers
              regexp='^Defaults    requiretty'
              line='#Defaults    requiretty'

- name: Deploy bdshr config
  shell:
    ./bdshr_config_installer.sh
    chdir={{bahmni_packages_build_path}}
  environment:
    FACTER_deploy_bahmni_openerp: false
    FACTER_deploy_bahmni_openelis: true
    FACTER_implementation_name: bdshr
    FACTER_bahmni_user_name: bahmni

- name: Stop openerp service
  service: name=openerp state=stopped

- name: Restart tomcat
  service: name=tomcat state=restarted