---

- name: Copy config
  copy: src={{ item }} dest=/tmp mode=0777
  with_fileglob:
    - "{{ config_file }}"

- name: Deploy bdshr config
  shell:
    /tmp/{{ config_file }}
  environment:
    FACTER_deploy_bahmni_openerp: false
    FACTER_deploy_bahmni_openelis: "{{ deploy_openelis }}"
    FACTER_implementation_name: "{{ implementation_config_name }}"
    FACTER_bahmni_user_name: bahmni
